### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by keennandebie** [skrollme/homebridge-people-x#7]
I get this error while running Homebridge. I had no problem when running on macOS, but it doesn't work on a raspberry.

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-people-x/node_modules/node-persist/storage'
    at Object.mkdirSync (fs.js:841:3)
    at sync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/mkdirp/index.js:55:12)
    at sync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/mkdirp/index.js:61:24)
    at Function.sync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/mkdirp/index.js:61:24)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/node-persist/local-storage.js:615:20)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/node-persist/local-storage.js:545:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/node-persist/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-people-x/node_modules/node-persist/node-persist.js:41:29)
    at new PeoplePlatform (/usr/local/lib/node_modules/homebridge-people-x/index.js:39:18)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)

**Comment by NainRouge** [comment]
Same issue, be nice if the dev chimed in

**Comment by skrollme** [comment]
As the error message says: `permission denied, mkdir '/usr/local/lib/node_modules/homebridge-people-x/node_modules/node-persist/storage'`
The plugin/homebridge tries to create a directory which is not allowed in your setup. You can solve this with some unix-knowledge by yourself

**Comment by NainRouge** [comment]
And those without *nix knowledge don’t deserve to use the plugin, amirite?

**Comment by krishagel** [comment]
sudo chown -R pi: /usr/local/lib/node_modules/homebridge-people-x will change ownership of the folder it is creating and should allow you to resolve this.
